export default [
  {
    id: 1,
    title: "title",
    description: "description",
    technology: ["html"],
    github: "",
    demo: "",
  },
  {
    id: 2,
    title: "title",
    description: "description",
    technology: ["html"],
    github: "",
    demo: "",
  },
  {
    id: 3,
    title: "title",
    description: "description",
    technology: ["html"],
    github: "",
    demo: "",
  },
  {
    id: 4,
    title: "title",
    description: "descrption",
    technology: ["html"],
    github: "",
    demo: "",
  },
  {
    id: 5,
    title: "title",
    description: "descrption",
    technology: ["html"],
    github: "",
    demo: "",
  },
  {
    id: 6,
    title: "title",
    description: "descrption",
    technology: ["html"],
    github: "",
    demo: "",
  },
];
